version: "3"

networks: 
  dbnet: 

volumes: 
  dbvol: 
    
services:
  backend: 
    image: postgres:13.3-alpine
    volumes:
      - dbvol:/var/lib/postgresql/data
    networks:
      - dbnet
    environment:
      - POSTGRES_PASSWORD=something
      - POSTGRES_USER=admin

  frontend:
    image: adminer:4.8.1-standalone
    networks:
      - dbnet
    ports:
      - 8080
    environment:
      - ADMINER_DEFAULT_SERVER=backend
       
